/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('nl' | 'en') | ('nl' | 'en')[];
  globals: {
    home: Home;
    diensten: Diensten;
    portfolio: Portfolio;
    'over-ons': OverOn;
    contact: Contact;
    privacyverklaring: Privacyverklaring;
    'niet-gevonden': NietGevonden;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    diensten: DienstenSelect<false> | DienstenSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    'over-ons': OverOnsSelect<false> | OverOnsSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    privacyverklaring: PrivacyverklaringSelect<false> | PrivacyverklaringSelect<true>;
    'niet-gevonden': NietGevondenSelect<false> | NietGevondenSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'nl' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Beheerders kunnen alles. Redacteuren bewerken alleen de pagina-inhoud.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * De losse dienstpagina's (binnenschilderwerk, behangen, beglazing, ...).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Zonder spaties. Bepaalt het paginapad.
   */
  slug: string;
  eyebrow?: string | null;
  heading?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  inlineImage?: (number | null) | Media;
  ctaPrimary?: string | null;
  ctaSecondary?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eyebrow?: T;
  heading?: T;
  heroImage?: T;
  body?: T;
  inlineImage?: T;
  ctaPrimary?: T;
  ctaSecondary?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    image?: (number | null) | Media;
  };
  trust?:
    | {
        icon?: string | null;
        title?: string | null;
        subtitle?: string | null;
        id?: string | null;
      }[]
    | null;
  servicesIntro?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
  };
  servicesCards?:
    | {
        title?: string | null;
        text?: string | null;
        image?: (number | null) | Media;
        raised?: boolean | null;
        id?: string | null;
      }[]
    | null;
  about?: {
    eyebrow?: string | null;
    title?: string | null;
    image?: (number | null) | Media;
    badgeNumber?: string | null;
    badgeLabel?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
  };
  portfolioIntro?: {
    eyebrow?: string | null;
    title?: string | null;
  };
  portfolio?:
    | {
        category?: string | null;
        title?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  reviewsIntro?: {
    eyebrow?: string | null;
    title?: string | null;
    score?: string | null;
    count?: string | null;
  };
  reviews?:
    | {
        quote?: string | null;
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    title?: string | null;
    text?: string | null;
    button?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diensten".
 */
export interface Diensten {
  id: number;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
  };
  binnenwerk?: {
    eyebrow?: string | null;
    heading?: string | null;
    items?:
      | {
          categoryLabel?: string | null;
          title?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          text?: string | null;
          linkHref?: string | null;
          linkLabel?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  buitenwerk?: {
    eyebrow?: string | null;
    heading?: string | null;
    items?:
      | {
          categoryLabel?: string | null;
          title?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          text?: string | null;
          linkHref?: string | null;
          linkLabel?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    title?: string | null;
    text?: string | null;
    button?: string | null;
    href?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
  };
  filters?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  projects?:
    | {
        cat?: string | null;
        colSpan?: string | null;
        image?: (number | null) | Media;
        imageAlt?: string | null;
        categoryLabel?: string | null;
        title?: string | null;
        description?: string | null;
        size?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    title?: string | null;
    text?: string | null;
    button?: string | null;
    href?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "over-ons".
 */
export interface OverOn {
  id: number;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    image?: (number | null) | Media;
    imageAlt?: string | null;
  };
  values?: {
    eyebrow?: string | null;
    heading?: string | null;
    items?:
      | {
          icon?: string | null;
          title?: string | null;
          text?: string | null;
          raised?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  team?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    quote?: string | null;
    image1?: (number | null) | Media;
    image1Alt?: string | null;
    image2?: (number | null) | Media;
    image2Alt?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  hero?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: string | null;
  };
  infoCard?: {
    heading?: string | null;
    addressLabel?: string | null;
    phoneLabel?: string | null;
    emailLabel?: string | null;
  };
  businessCard?: {
    heading?: string | null;
    kvkLabel?: string | null;
    bankLabel?: string | null;
    accountLabel?: string | null;
  };
  form?: {
    heading?: string | null;
    intro?: string | null;
    labelName?: string | null;
    labelPhone?: string | null;
    labelMobile?: string | null;
    labelEmail?: string | null;
    labelCopy?: string | null;
    labelCity?: string | null;
    labelUitvoeringMonth?: string | null;
    labelWerkzaamheden?: string | null;
    optionChoose?: string | null;
    optionSchilderen?: string | null;
    optionBehangen?: string | null;
    optionOnderhoud?: string | null;
    optionAfgeschermd?: string | null;
    optionBeglazing?: string | null;
    optionRamen?: string | null;
    labelMessage?: string | null;
    labelPrivacy?: string | null;
    labelPrivacyLink?: string | null;
    submitButton?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacyverklaring".
 */
export interface Privacyverklaring {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  lastUpdated?: string | null;
  contactEmail?: string | null;
  backLink?: string | null;
  sections?:
    | {
        heading?: string | null;
        html?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "niet-gevonden".
 */
export interface NietGevonden {
  id: number;
  heading?: string | null;
  body?: string | null;
  linkHome?: string | null;
  linkContact?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  company: {
    name: string;
    shortName?: string | null;
    tagline?: string | null;
    founded?: string | null;
    yearsExperience?: string | null;
  };
  contact?: {
    addressLine1?: string | null;
    addressLine2?: string | null;
    phoneDisplay?: string | null;
    phoneHref?: string | null;
    email?: string | null;
  };
  business?: {
    kvk?: string | null;
    bankName?: string | null;
    bankAccount?: string | null;
  };
  navServices?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  credit?: {
    name?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        image?: T;
      };
  trust?:
    | T
    | {
        icon?: T;
        title?: T;
        subtitle?: T;
        id?: T;
      };
  servicesIntro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
      };
  servicesCards?:
    | T
    | {
        title?: T;
        text?: T;
        image?: T;
        raised?: T;
        id?: T;
      };
  about?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        image?: T;
        badgeNumber?: T;
        badgeLabel?: T;
        paragraph1?: T;
        paragraph2?: T;
      };
  portfolioIntro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  portfolio?:
    | T
    | {
        category?: T;
        title?: T;
        image?: T;
        id?: T;
      };
  reviewsIntro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        score?: T;
        count?: T;
      };
  reviews?:
    | T
    | {
        quote?: T;
        name?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
        button?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diensten_select".
 */
export interface DienstenSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
      };
  binnenwerk?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              categoryLabel?: T;
              title?: T;
              image?: T;
              imageAlt?: T;
              text?: T;
              linkHref?: T;
              linkLabel?: T;
              id?: T;
            };
      };
  buitenwerk?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              categoryLabel?: T;
              title?: T;
              image?: T;
              imageAlt?: T;
              text?: T;
              linkHref?: T;
              linkLabel?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
        button?: T;
        href?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
      };
  filters?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  projects?:
    | T
    | {
        cat?: T;
        colSpan?: T;
        image?: T;
        imageAlt?: T;
        categoryLabel?: T;
        title?: T;
        description?: T;
        size?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
        button?: T;
        href?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "over-ons_select".
 */
export interface OverOnsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        ctaLabel?: T;
        ctaHref?: T;
        image?: T;
        imageAlt?: T;
      };
  values?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              raised?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph1?: T;
        paragraph2?: T;
        ctaLabel?: T;
        ctaHref?: T;
        quote?: T;
        image1?: T;
        image1Alt?: T;
        image2?: T;
        image2Alt?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
      };
  infoCard?:
    | T
    | {
        heading?: T;
        addressLabel?: T;
        phoneLabel?: T;
        emailLabel?: T;
      };
  businessCard?:
    | T
    | {
        heading?: T;
        kvkLabel?: T;
        bankLabel?: T;
        accountLabel?: T;
      };
  form?:
    | T
    | {
        heading?: T;
        intro?: T;
        labelName?: T;
        labelPhone?: T;
        labelMobile?: T;
        labelEmail?: T;
        labelCopy?: T;
        labelCity?: T;
        labelUitvoeringMonth?: T;
        labelWerkzaamheden?: T;
        optionChoose?: T;
        optionSchilderen?: T;
        optionBehangen?: T;
        optionOnderhoud?: T;
        optionAfgeschermd?: T;
        optionBeglazing?: T;
        optionRamen?: T;
        labelMessage?: T;
        labelPrivacy?: T;
        labelPrivacyLink?: T;
        submitButton?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacyverklaring_select".
 */
export interface PrivacyverklaringSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lastUpdated?: T;
  contactEmail?: T;
  backLink?: T;
  sections?:
    | T
    | {
        heading?: T;
        html?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "niet-gevonden_select".
 */
export interface NietGevondenSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  linkHome?: T;
  linkContact?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  company?:
    | T
    | {
        name?: T;
        shortName?: T;
        tagline?: T;
        founded?: T;
        yearsExperience?: T;
      };
  contact?:
    | T
    | {
        addressLine1?: T;
        addressLine2?: T;
        phoneDisplay?: T;
        phoneHref?: T;
        email?: T;
      };
  business?:
    | T
    | {
        kvk?: T;
        bankName?: T;
        bankAccount?: T;
      };
  navServices?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  credit?:
    | T
    | {
        name?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}