import type { GlobalConfig } from 'payload'

export const ContactPage: GlobalConfig = {
  slug: 'contact',
  label: 'Contact',
  admin: {
    group: "Pagina's",
    description: 'Alle teksten op de contactpagina: hero, contactgegevens, bedrijfskaart en het aanvraagformulier.',
  },
  access: { read: () => true },
  fields: [
    {
      type: 'group',
      name: 'hero',
      label: 'Hero-sectie',
      localized: true,
      fields: [
        { name: 'eyebrow', type: 'text', label: 'Bovenkop' },
        { name: 'heading', type: 'text', label: 'Kop' },
        { name: 'intro', type: 'textarea', label: 'Introductietekst' },
      ],
    },
    {
      type: 'group',
      name: 'infoCard',
      label: 'Contactgegevens kaart (labels)',
      localized: true,
      fields: [
        { name: 'heading', type: 'text', label: 'Kop' },
        { name: 'addressLabel', type: 'text', label: 'Label adres' },
        { name: 'phoneLabel', type: 'text', label: 'Label telefoon' },
        { name: 'emailLabel', type: 'text', label: 'Label e-mail' },
      ],
    },
    {
      type: 'group',
      name: 'businessCard',
      label: 'Bedrijfsgegevens kaart (labels)',
      localized: true,
      fields: [
        { name: 'heading', type: 'text', label: 'Kop' },
        { name: 'kvkLabel', type: 'text', label: 'Label KvK' },
        { name: 'bankLabel', type: 'text', label: 'Label bank' },
        { name: 'accountLabel', type: 'text', label: 'Label rekeningnummer' },
      ],
    },
    {
      type: 'group',
      name: 'form',
      label: 'Formulier teksten',
      localized: true,
      fields: [
        { name: 'heading', type: 'text', label: 'Kop' },
        { name: 'intro', type: 'textarea', label: 'Introductietekst' },
        { name: 'labelName', type: 'text', label: 'Label naam' },
        { name: 'labelPhone', type: 'text', label: 'Label telefoonnummer' },
        { name: 'labelMobile', type: 'text', label: 'Label mobiel' },
        { name: 'labelEmail', type: 'text', label: 'Label e-mailadres' },
        { name: 'labelCopy', type: 'text', label: 'Label kopie aanvraag' },
        { name: 'labelCity', type: 'text', label: 'Label woonplaats' },
        { name: 'labelUitvoeringMonth', type: 'text', label: 'Label gewenste maand' },
        { name: 'labelWerkzaamheden', type: 'text', label: 'Label werkzaamheden' },
        { name: 'optionChoose', type: 'text', label: 'Optie: maak een keuze' },
        { name: 'optionSchilderen', type: 'text', label: 'Optie: schilderen' },
        { name: 'optionBehangen', type: 'text', label: 'Optie: behangen' },
        { name: 'optionOnderhoud', type: 'text', label: 'Optie: onderhoud' },
        { name: 'optionAfgeschermd', type: 'text', label: 'Optie: afgeschermd onderhoud' },
        { name: 'optionBeglazing', type: 'text', label: 'Optie: beglazing' },
        { name: 'optionRamen', type: 'text', label: 'Optie: ramen zetten' },
        { name: 'labelMessage', type: 'text', label: 'Label aanvullende informatie' },
        { name: 'labelPrivacy', type: 'text', label: 'Label privacytekst (voor link)' },
        { name: 'labelPrivacyLink', type: 'text', label: 'Label privacylink' },
        { name: 'submitButton', type: 'text', label: 'Knoptekst versturen' },
      ],
    },
  ],
}
